config/routes.rb
Blendwith::Application.routes.draw do

  root :to => "public#index"

  get "/tour" => "public#tour"
  opinio_model :controller => 'my_comments'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :video_urls
  resources :uploaded_photos
  resources :collections

  resources :music_urls do
    post :create_all, :on => :collection
  end

  resources :photo_urls, :only => [:new, :create, :destroy, :update] do
    delete 'delete_many', :on => :collection
  end

  match '/auth/:provider/callback' => 'services#create'
  resources :services, :only => [:index, :create]

  match "/facebook" => "image_playlists#show"
  match "/instagram" => "image_playlists#show"
  match "/googleplus" => "image_playlists#show"
  match "/twitter" => "image_playlists#show"
  match "/flickr" => "image_playlists#show"
  match "/soundcloud" => "music_playlists#show"
  match "/youtube" => "video_playlists#show"

  match "/uploader" => "photo_networks#uploader"
  put "/update_uploader/:id" => "photo_networks#update_uploader", :as => :update_photo_uploader

  post "/playlist_box_session" => "home#playlist_box_session"
  get "home/:social/social_login" => "home#social_login"
  get "/tour/update"    => "friend_maps#update_tour"

  devise_for :users, :controllers => { :omniauth_callbacks => 'services', :sessions => "users/sessions" }

  resources :playlists, :only => [:update, :destroy] do
    post :toggle_feed, :on => :member
  end

  resources :image_playlists do
    post 'add_item', :on => :member
    delete 'delete_media', :on => :collection
    get :image_playlist_by_id, :on => :member
    get :background_music_list, :on => :collection
    get :recent, :on => :collection
  end
  
  resources :music_playlists do
    post 'add_item', :on => :member
    delete :delete_item, :on => :collection
    put :update_track, :on => :member, :as => :update_track
  end

  resources :video_playlists do
    post 'add_item', :on => :member
    delete :delete_item, :on => :collection
  end

  get "/embed/:token" => "users#embed"

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :inbox
      get :sent_box
      get :trash_box
    end
  end

  resources :users, :only => [:show, :edit, :update, :destroy] do
    opinio
    post :privacy, :on => :collection
    post :friend_request, :on => :collection
    get :connect_social_network, :on => :collection
    post :disconnect_social_network, :on => :collection
    put :update_password, :on => :collection
    get :new_twitter_user, :on => :collection
    post :create_twitter_user, :on => :collection
    get :user_comments, :on => :member
    resources :uploaded_photos do
      collection do
        post :upload_photos
      end
    end
    resources :cover_photos do
      collection do
        post :upload_photos
      end
    end
    resources :profile_photos do
      collection do
        post :upload_photos
      end
    end
  end

  post "users/user-gallery.php" => "users#user_gallery"
  post "users/ajax-gallery.php" => "users#ajax_gallery"
  post "users/player.php" => "users#player"
  post "users/user_gallery_album" => "users#user_gallery_album"
  post "users/photo_player" => "users#photo_player"

  resources :uploaded_videos do
    post :authorize_upload, :on => :collection
  end

  resources :uploaded_audios do
    post :authorize_upload, :on => :collection
  end

  resources :ajax, :controller => :ajax, :only => :none do
    get :soundcloud_embed, :on => :collection
  end
  get "/feed/:item_id/toggler" => "ajax#feed_item_toggler", :as => :feed_toggler
  get "/change/:playlist_id/cover_from/:item_id" => "ajax#change_playlist_cover_from_media", :as => :playlist_cover_changer

  resources :friend_maps do
    get :pending_friends, :on => :collection
    get :request_friends, :on => :collection
    get :friends, :on => :collection
    post :add_friend, :on => :collection
    post :agree_request, :on => :collection
    get :friends_feed, :on => :collection
  end

  resources :photos, :only => [:show, :update, :destroy]
  resources :albums, :only => [:show, :update, :destroy] do
    delete :delete_photo, :on => :collection
  end
  resources :tracks, :only => [:show, :update, :destroy]
  resources :videos, :only => [:show, :update, :destroy] do
    member do
      get :preview
    end
  end

  get '/:username' => "users#show"

  resources :track_albums, :only => [:show] do
    delete :delete_track, :on => :collection
  end

  resources :video_albums, :only => [:show] do
    delete :delete_video, :on => :collection
  end

 match '/users/sign_in' => "devise/sessions#new", :as => :create_user_session

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  layout 'friend'

  before_filter :authenticate_user!

  skip_before_filter :verify_authenticity_token, :only => [:trash, :untrash, :reply]

  helper_method :mailbox, :conversation

  def index
    @which_box = params[:which_box] || 'inbox'
    if params[:conversation]
      @conversation = Conversation.find(params[:conversation])
      @receipts = @conversation.receipts_for(current_user).order('created_at asc')
    end
  end

  def inbox
    @conversations = mailbox.inbox.page(params[:page]).per(12)
  end

  def sent_box
    @conversations = mailbox.sentbox.page(params[:page]).per(12)
  end

  def trash_box
    @is_trash = true
    @conversations = mailbox.trash.page(params[:page]).per(12)
  end

  def new
    @user = User.find params[:send_to]
  end

  def show
    @conversation = Conversation.find params[:id]
    @receipts = @conversation.receipts_for(current_user).order('created_at asc')
    render :json => {html: render_to_string(:partial => 'conversations/show')}
    @receipts.mark_as_read
  end

  #recipient_emails = conversation_params(:recipients).split(',')
  #recipients = User.where(email
  # : recipient_emails).all
  def create
    user = User.find params[:conversation][:recipients]
    conver = current_user.send_message(user, *conversation_params(:body, :subject)).conversation
    redirect_to "#{conversations_url}?which_box=sent_box&conversation=#{conver.id}"
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
  end

  def trash
    conversation.move_to_trash(current_user)
  end

  def untrash
    conversation.untrash(current_user)
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
    @receipts ||= @conversation.receipts_for(current_user).order('created_at asc')
    @conversation
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end
end

app/views/conversations/_conversation.html.erb
<%= content_tag_for(:li, conversation) do |conversation| %>
    <p>
        <%= link_to conversation.subject, conversation %>
        |
        <% if conversation.is_completely_trashed?(current_user) %>
            <%= link_to 'Untrash', [:untrash, conversation], method: :post %>
        <% else %>
            <%= link_to 'Move to trash', [:trash, conversation], method: :post %>
        <% end %>
    </p>
<% end %>

app/views/conversations/_conversation_list.html.erb
<% @conversations.each do |conversation| %>
    <% unread_count = conversation.receipts_for(current_user).where(is_read: false).count %>
    <% read_status = (unread_count == 0) ? 'read-message' : 'unread-message' %>
    <li>
      <p>
        <%= link_to conversation.subject, conversation_path(conversation), class: "show-message #{read_status}" %>
        &nbsp;|&nbsp;
        <% if @is_trash %>
            <%= link_to 'Untrash', untrash_conversation_path(conversation), class: read_status, remote: true, method: :post %>
        <% else %>
            <%= link_to 'Move to trash', trash_conversation_path(conversation), class: read_status, remote: true, method: :post %>
        <% end %>
      </p>
    </li>
<% end %>
<li>
  <%= paginate @conversations, remote: true %>
</li>

app/views/conversations/_form.html.erb
<%= simple_form_for :conversation, url: :conversations do |f| %>
    <%= f.input :recipients, as: :hidden, :input_html => { :value => @user.id }  %>
    <%= f.input :subject, :input_html => {style: 'width: 500px;'} %>
    <%= f.input :body, as: :text, :input_html => { :cols => 50, :rows => 10, :style => 'width: 500px;' } %>
    <div class="form-actions" style="padding-left: 0">
      <%= f.button :submit, class: 'btn btn-wuxia btn-normal btn-primary' %>
      <%#= submit_tag 'Cancel', type: :reset, class: 'btn btn-wuxia btn-normal btn-danger' %>
    </div>
<% end %>

app/views/conversations/_show.html.erb
<h1><%= @conversation.subject %></h1>
<ul>
    <%= content_tag_for(:li, @receipts) do |receipt| %>
        <% message = receipt.message %>
        <div class="<%= receipt.is_unread? ? 'unread' : 'read' %>">
          <h3><%= message.subject %></h3>
          <p>
            <%= message.body.html_safe %>
          </p>
        </div>
    <% end %>
</ul>
<%= render 'messages/form', conversation: @conversation %>

app/views/conversations/inbox.js.erb
$('#search_result .message-list').html('<%= escape_javascript render('conversation_list') %>')

app/views/conversations/index.html.erb
<script type="text/javascript">
  $(function(){
      $.get('/conversations/inbox', {}, null, 'script');
      $.get('/conversations/sent_box', {}, null, 'script');
      $.get('/conversations/trash_box', {}, null, 'script');
  })
</script>

<div style="width: 100%;background: url(/assets/grid.png);">
  <div style="width: 1200px;padding: 30px 0 0 80px;margin: 0 auto;">
    <ul id="friend_ul" class="nav nav-tabs" style="margin: 0">
      <li class="<%= (@which_box == 'inbox' ? 'active' : '') %>">
        <a href="#" id="all_btn">Inbox</a>
        <!--&nbsp;<span class="badge badge-important"><%#= 0 %></span>-->
      </li>
      <li class="<%= @which_box == 'sent_box' ? 'active' : '' %>"><a href="#" id="pending_btn">Sentbox</a></li>
      <li class="<%= @which_box == 'trash_box' ? 'active' : '' %>"><a href="#" id="request_btn">Trash</a></li>
    </ul>
  </div>
</div>

<div style="width: 100%;background: #F6F6F6;">
  <div style="width: 1200px;padding: 0 0 0 80px;margin: 0 auto;">
    <div id="search_result" class="message-panel" style="display: <%= @which_box == 'inbox' ? 'block' : 'none' %>">
      <ul class="message-list"></ul>
      <div class="message-content"></div>
    </div>
    <div id="pending_friends" class="message-panel" style="display: <%= @which_box == 'sent_box' ? 'block' : 'none' %>">
      <ul class="message-list"></ul>
      <div class="message-content">
        <% if @which_box == 'sent_box' %>
            <%= render 'show' if @conversation %>
        <% end %>
      </div>
    </div>
    <div id="request_friends" class="message-panel" style="display: <%= @which_box == 'trash_box' ? 'block' : 'none' %>">
      <ul class="message-list"></ul>
      <div class="message-content"></div>
    </div>
  </div>
</div>

app/views/conversations/new.html.erb
<div style="width: 100%;background: url(/assets/grid.png);">
  <div style="width: 1200px;padding: 30px 0 0 80px;margin: 0 auto;">
    <ul id="friend_ul" class="nav nav-tabs" style="margin: 0">
      <li class="active">
        <a href="javascript:void(0)">
          <h4>Send a new message to <%= @user.full_name %></h4>
        </a>
      </li>
    </ul>
  </div>
</div>

<div style="width: 100%;background: #F6F6F6;">
  <div style="width: 1200px;padding: 0 0 0 80px;margin: 0 auto;">
    <%= render 'form' %>
  </div>
</div>

app/views/conversations/reply.js.erb
$('.message-panel:visible .message-content').html('<%= escape_javascript render('show') %>');

app/views/conversations/sent_box.js.erb
$('#pending_friends .message-list').html('<%= escape_javascript render('conversation_list') %>')

app/views/conversations/show.html.erb
<%# this is useless now %>
<h1><%= @conversation.subject %></h1>
<ul>
    <%= content_tag_for(:li, @conversation.receipts_for(current_user)) do |receipt| %>
        <% message = receipt.message %>
        <h3><%= message.subject %></h3>
        <p>
          <%= message.body %>
        </p>
    <% end %>
</ul>
<%= render 'messages/form', conversation: @conversation %>

app/views/conversations/trash.js.erb
$.get('/conversations/inbox', {}, null, 'script');
$.get('/conversations/sent_box', {}, null, 'script');
$.get('/conversations/trash_box', {}, null, 'script');

app/views/conversations/trash_box.js.erb
$('#request_friends .message-list').html('<%= escape_javascript render('conversation_list') %>')

app/views/conversations/untrash.js.erb
$.get('/conversations/inbox', {}, null, 'script');
$.get('/conversations/sent_box', {}, null, 'script');
$.get('/conversations/trash_box', {}, null, 'script');