config/routes.rb
Blendwith::Application.routes.draw do

  root :to => "public#index"

  get "/tour" => "public#tour"
  opinio_model :controller => 'my_comments'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :video_urls
  resources :uploaded_photos
  resources :collections

  resources :music_urls do
    post :create_all, :on => :collection
  end

  resources :photo_urls, :only => [:new, :create, :destroy, :update] do
    delete 'delete_many', :on => :collection
  end

  match '/auth/:provider/callback' => 'services#create'
  resources :services, :only => [:index, :create]

  match "/facebook" => "image_playlists#show"
  match "/instagram" => "image_playlists#show"
  match "/googleplus" => "image_playlists#show"
  match "/twitter" => "image_playlists#show"
  match "/flickr" => "image_playlists#show"
  match "/soundcloud" => "music_playlists#show"
  match "/youtube" => "video_playlists#show"

  match "/uploader" => "photo_networks#uploader"
  put "/update_uploader/:id" => "photo_networks#update_uploader", :as => :update_photo_uploader

  post "/playlist_box_session" => "home#playlist_box_session"
  get "home/:social/social_login" => "home#social_login"
  get "/tour/update"    => "friend_maps#update_tour"

  devise_for :users, :controllers => { :omniauth_callbacks => 'services', :sessions => "users/sessions" }

  resources :playlists, :only => [:update, :destroy] do
    post :toggle_feed, :on => :member
  end

  resources :image_playlists do
    post 'add_item', :on => :member
    delete 'delete_media', :on => :collection
    get :image_playlist_by_id, :on => :member
    get :background_music_list, :on => :collection
    get :recent, :on => :collection
  end
  
  resources :music_playlists do
    post 'add_item', :on => :member
    delete :delete_item, :on => :collection
    put :update_track, :on => :member, :as => :update_track
  end

  resources :video_playlists do
    post 'add_item', :on => :member
    delete :delete_item, :on => :collection
  end

  get "/embed/:token" => "users#embed"

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :inbox
      get :sent_box
      get :trash_box
    end
  end

  resources :users, :only => [:show, :edit, :update, :destroy] do
    opinio
    post :privacy, :on => :collection
    post :friend_request, :on => :collection
    get :connect_social_network, :on => :collection
    post :disconnect_social_network, :on => :collection
    put :update_password, :on => :collection
    get :new_twitter_user, :on => :collection
    post :create_twitter_user, :on => :collection
    get :user_comments, :on => :member
    resources :uploaded_photos do
      collection do
        post :upload_photos
      end
    end
    resources :cover_photos do
      collection do
        post :upload_photos
      end
    end
    resources :profile_photos do
      collection do
        post :upload_photos
      end
    end
  end

  post "users/user-gallery.php" => "users#user_gallery"
  post "users/ajax-gallery.php" => "users#ajax_gallery"
  post "users/player.php" => "users#player"
  post "users/user_gallery_album" => "users#user_gallery_album"
  post "users/photo_player" => "users#photo_player"

  resources :uploaded_videos do
    post :authorize_upload, :on => :collection
  end

  resources :uploaded_audios do
    post :authorize_upload, :on => :collection
  end

  resources :ajax, :controller => :ajax, :only => :none do
    get :soundcloud_embed, :on => :collection
  end
  get "/feed/:item_id/toggler" => "ajax#feed_item_toggler", :as => :feed_toggler
  get "/change/:playlist_id/cover_from/:item_id" => "ajax#change_playlist_cover_from_media", :as => :playlist_cover_changer

  resources :friend_maps do
    get :pending_friends, :on => :collection
    get :request_friends, :on => :collection
    get :friends, :on => :collection
    post :add_friend, :on => :collection
    post :agree_request, :on => :collection
    get :friends_feed, :on => :collection
  end

  resources :photos, :only => [:show, :update, :destroy]
  resources :albums, :only => [:show, :update, :destroy] do
    delete :delete_photo, :on => :collection
  end
  resources :tracks, :only => [:show, :update, :destroy]
  resources :videos, :only => [:show, :update, :destroy] do
    member do
      get :preview
    end
  end

  get '/:username' => "users#show"

  resources :track_albums, :only => [:show] do
    delete :delete_track, :on => :collection
  end

  resources :video_albums, :only => [:show] do
    delete :delete_video, :on => :collection
  end

 match '/users/sign_in' => "devise/sessions#new", :as => :create_user_session

end

app/views/shared/_audio_player.html.erb
<script type="text/javascript">
    $(document).ready(function () {
        $("#jquery_jplayer_1").jPlayer({
            ready: function () {
            },
            swfPath: "/js",
            supplied: "m4a, oga"
        });

        $(".music-label input").click(function () {
            var music = $(this).val();
            $("#jquery_jplayer_1").jPlayer("setMedia", { m4a: music });
            $(".jp-title ul li").html($(this).parent().text());
            $("#jquery_jplayer_1").jPlayer("play");
        });
    });
</script>

<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div id="jp_container_1" class="jp-audio">
  <div class="jp-type-single">
    <div class="jp-gui jp-interface">
      <ul class="jp-controls">
        <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
        <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
        <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
        <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
        <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
        <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
      </ul>
      <div class="jp-progress">
        <div class="jp-seek-bar">
          <div class="jp-play-bar"></div>
        </div>
      </div>
      <div class="jp-volume-bar">
        <div class="jp-volume-bar-value"></div>
      </div>
      <div class="jp-time-holder">
        <div class="jp-current-time"></div>
        <div class="jp-duration"></div>
        <ul class="jp-toggles">
          <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
          <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
        </ul>
      </div>
    </div>
    <div class="jp-title">
      <ul>
        <li>Player</li>
      </ul>
    </div>
    <div class="jp-no-solution">
      <span>Update Required</span>
      To play the media you will need to either update your browser to a recent version or update your
      <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
    </div>
  </div>
</div>

app/views/shared/_audiojs_player.html.erb
<div class="audiojs " classname="audiojs" id="audiojs_wrapper0">
  <audio preload></audio>          
  <div class="prev-pl"></div>
  <div class="next-pl"></div>
  <div class="music-cloud"></div>
  <div id="vol-bf"><img src="/assets/volume-bf.png"></div>
  <div id="vol-af"><img src="/assets/volume-uf.png"></div>
  <div id="volume"></div>
</div>

app/views/shared/_cp_audio_player.html.erb
<script type="text/javascript">
    $(document).ready(function () {
        var myCirclePlayer = new CirclePlayer("#cp_jplayer_1",
                {
//                    m4a: "http://www.jplayer.org/audio/m4a/Miaow-07-Bubble.m4a",
//                    oga: "http://www.jplayer.org/audio/ogg/Miaow-07-Bubble.ogg"
                }, {
                    cssSelectorAncestor: "#cp_container_1"
                });
    });
</script>

<div id="cp_jplayer_1" class="cp-jplayer"></div>

<!-- The container for the interface can go where you want to display it. Show and hide it as you need. -->

<div id="cp_container_1" class="cp-container">
  <div class="cp-buffer-holder"> <!-- .cp-gt50 only needed when buffer is > than 50% -->
    <div class="cp-buffer-1"></div>
    <div class="cp-buffer-2"></div>
  </div>
  <div class="cp-progress-holder"> <!-- .cp-gt50 only needed when progress is > than 50% -->
    <div class="cp-progress-1"></div>
    <div class="cp-progress-2"></div>
  </div>
  <div class="cp-circle-control"></div>
  <ul class="cp-controls">
    <li><a class="cp-play" tabindex="1">play</a></li>
    <li><a class="cp-pause" style="display:none;" tabindex="1">pause</a></li>
    <!-- Needs the inline style here, or jQuery.show() uses display:inline instead of display:block -->
  </ul>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-error">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <h4><%= t(pluralize(object.errors.count, "error")) %> prohibited this user from being saved:</h4>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_image_playlist_setting.html.erb
<div style="position: fixed;top: 78px;">
<%= form_for @playlist_show do |f| %>
    <fieldset>
      <div class="control-group">
        <label class="control-label" for="input">Caption</label>

        <div class="controls">
          <%= f.text_field :name, class: 'input-xlarge', placeholder: 'Caption here' %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="optionsCheckbox">Slideshow</label>
        <div class="controls">
          <label class="checkbox">
            <%= f.check_box :slide_show %>
            on
          </label>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="select">Transition</label>
        <div class="controls">
          <%= f.select :transition, options_for_select([['None', 'None'],['Slide','Slide'],['Dissolve','Dissolve']], @playlist_show.transition) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input">Delay (In Secs)</label>
        <div class="controls">
          <%= f.select :delay_second, options_for_select((1..10).collect {|x| [x, x] }, @playlist_show.delay_second) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input">Background Music</label>
        <div class="controls">
          <!--<input class="input-xlarge" type="text" name="tags" placeholder="Background Music (from my music library)">-->
          <%= f.hidden_field :background_music_id, :id => 'background_music_id' %>
          <%= f.hidden_field :background_music_type, :id => 'background_music_type' %>
          <%= f.hidden_field :background_music_url, :id => 'background_music_url' %>
          <%= f.hidden_field :background_music_title, :id => 'background_music_title' %>
          <label id="background_music_title_label"><%= @playlist_show.background_music_title %></label>
          <a href="#" class="btn" id="choose_music">Select Music</a>
        </div>
      </div>

      <div class="form-actions">
        <button class="btn btn-wuxia btn-normal btn-primary" type="submit">Save changes</button>
        <a class="btn btn-wuxia btn-normal btn-primary close-form">Cancel</a>
        <%= link_to 'Delete', image_playlist_path(@playlist_show), class: 'btn btn-wuxia btn-normal btn-danger', confirm: 'Are you sure?', method: :delete  %>
      </div>
    </fieldset>
<% end %>
</div>

app/views/shared/_image_playlist_setting_load_music.html.erb
<input type="hidden" id="music_not_load" />
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3>Select Background Music For Slide Show</h3>
  <input type="hidden"/><!-- store id -->
</div>
<div class="modal-body">
  <img src='/assets/icons/loading_dark.gif' style="display:block;margin: 0 auto;" />
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
</div>

app/views/shared/_image_playlist_setting_music.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3>Select Background Music For Slide Show</h3>
  <input type="hidden"/><!-- store id -->
</div>
<div class="modal-body">
  <ul>
    <li></li>
    <%# Actually, there is only Soundcloud here %>
    <% @playlists.each do |playlist| %>
        <% items = playlist.items %>
        <% items.each do |item| %>
            <% if item %>
                <% if item.itemizable.network == 'soundcloud' %>
                    <% music_url = item.itemizable %>
                    <% if music_url.class == Track %>
                        <%= content_tag :li, data: {id: music_url.social_network_id, type: 'Soundcloud', url: music_url.social_network_id, title: music_url.title}, class: 'span10' do %>
                            <label>
                              <input type="radio" name="music"/>
                              <%= music_url.title %>
                            </label>
                        <% end %>
                    <% elsif music_url.class == TrackAlbum %>
                        <% music_url.tracks.each do |track| %>
                            <%= content_tag :li, data: {id: track.social_network_id, type: 'Soundcloud', url: track.social_network_id, title: track.title}, class: 'span10' do %>
                                <label>
                                  <input type="radio" name="music"/>
                                  <%= track.title %>
                                </label>
                            <% end %>
                        <% end %>
                    <% end %>
                <% end %>
            <% end %>
        <% end %>
    <% end %>

    <% @audio_urls.each do |music_url| %>
        <%= content_tag :li, data: {id: music_url.id, type: 'URL_Audios', url: music_url.music_url, title: music_url.title}, class: 'span10' do %>
            <label>
              <input type="radio" name="music"/>
              <%= music_url.title %>
            </label>
        <% end %>
    <% end %>

    <% @uploaded_audios.each do |music_url| %>
        <%= content_tag :li, data: {id: music_url.id, type: 'Uploaded_Audios', url: music_url.ori_audio_url, title: music_url.title}, class: 'span10' do %>
            <label>
              <input type="radio" name="music"/>
              <%= music_url.title %>
            </label>
        <% end %>
    <% end %>
  </ul>
</div>
<div class="modal-footer">
  <button class="btn btn-primary choose_music">OK</button>
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
</div>

<script type="text/javascript">
    $(function () {
        $('button.choose_music').click(function () {
            if ($('li.span10 input[type="radio"]:checked').length == 1) {
                var li = $('li.span10 input[type="radio"]:checked').parent().parent();
                $("#background_music_id").val(li.attr('data-id'));
                $("#background_music_type").val(li.attr('data-type'));
                $("#background_music_url").val(li.attr('data-url'));
                $("#background_music_title").val(li.attr('data-title'));
                $("#background_music_title_label").html(li.attr('data-title'));
                $("#image-playlist-setting-panel").modal("hide");
            } else {
                $.jGrowl("Please select a music.", {
                    header: '',
                    sticky: true,
                    theme: 'info'
                });
            }
        });
    })
</script>

app/views/shared/_image_playlist_setting_wrapper.html.erb
<!--photo playlist setting-->
<div class="form slideshow-setting-div">
</div>

<!--choose music btn for photo playlist setting-->
<div id="image-playlist-setting-panel" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <%= render 'shared/image_playlist_setting_load_music' %>
</div>

app/views/shared/_set_feed.html.erb
<div id="set_feed_div" class="btn-group page-header-actions">
  <span class="btn">Set Feed</span>
  <span class="btn question-icon demoPopover" data-original-title="A Title" data-content="When you turn a Feed on for a particular service, Blendwith will automatically add new content from your account on that service to your Blendwith account. If a Feed is off, then you will have to manually add new content to Blendwith."><span class="awe-question-sign"></span></span>
  <button class="btn active" data-toggle="buttons-checkbox">On</button>
</div>

app/views/shared/_set_feed_new.html.erb
<div id="set_feed_div" class="btn-group page-header-actions">
  <span class="btn">Set Feed</span>
  <span class="btn question-icon demoPopover" data-original-title="A Title" data-content="When you turn a Feed on for a particular service, Blendwith will automatically add new content from your account on that service to your Blendwith account. If a Feed is off, then you will have to manually add new content to Blendwith."><span class="awe-question-sign"></span></span>
  <button data-id='<%= playlist_id %>' class="feed-btn btn <%= 'active' if set_feed %>" data-toggle="buttons-checkbox"><%= set_feed ? 'On' : 'Off' %></button>
</div>