config/routes.rb
Blendwith::Application.routes.draw do

  root :to => "public#index"

  get "/tour" => "public#tour"
  opinio_model :controller => 'my_comments'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :video_urls
  resources :uploaded_photos
  resources :collections

  resources :music_urls do
    post :create_all, :on => :collection
  end

  resources :photo_urls, :only => [:new, :create, :destroy, :update] do
    delete 'delete_many', :on => :collection
  end

  match '/auth/:provider/callback' => 'services#create'
  resources :services, :only => [:index, :create]

  match "/facebook" => "image_playlists#show"
  match "/instagram" => "image_playlists#show"
  match "/googleplus" => "image_playlists#show"
  match "/twitter" => "image_playlists#show"
  match "/flickr" => "image_playlists#show"
  match "/soundcloud" => "music_playlists#show"
  match "/youtube" => "video_playlists#show"

  match "/uploader" => "photo_networks#uploader"
  put "/update_uploader/:id" => "photo_networks#update_uploader", :as => :update_photo_uploader

  post "/playlist_box_session" => "home#playlist_box_session"
  get "home/:social/social_login" => "home#social_login"
  get "/tour/update"    => "friend_maps#update_tour"

  devise_for :users, :controllers => { :omniauth_callbacks => 'services', :sessions => "users/sessions" }

  resources :playlists, :only => [:update, :destroy] do
    post :toggle_feed, :on => :member
  end

  resources :image_playlists do
    post 'add_item', :on => :member
    delete 'delete_media', :on => :collection
    get :image_playlist_by_id, :on => :member
    get :background_music_list, :on => :collection
    get :recent, :on => :collection
  end
  
  resources :music_playlists do
    post 'add_item', :on => :member
    delete :delete_item, :on => :collection
    put :update_track, :on => :member, :as => :update_track
  end

  resources :video_playlists do
    post 'add_item', :on => :member
    delete :delete_item, :on => :collection
  end

  get "/embed/:token" => "users#embed"

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :inbox
      get :sent_box
      get :trash_box
    end
  end

  resources :users, :only => [:show, :edit, :update, :destroy] do
    opinio
    post :privacy, :on => :collection
    post :friend_request, :on => :collection
    get :connect_social_network, :on => :collection
    post :disconnect_social_network, :on => :collection
    put :update_password, :on => :collection
    get :new_twitter_user, :on => :collection
    post :create_twitter_user, :on => :collection
    get :user_comments, :on => :member
    resources :uploaded_photos do
      collection do
        post :upload_photos
      end
    end
    resources :cover_photos do
      collection do
        post :upload_photos
      end
    end
    resources :profile_photos do
      collection do
        post :upload_photos
      end
    end
  end

  post "users/user-gallery.php" => "users#user_gallery"
  post "users/ajax-gallery.php" => "users#ajax_gallery"
  post "users/player.php" => "users#player"
  post "users/user_gallery_album" => "users#user_gallery_album"
  post "users/photo_player" => "users#photo_player"

  resources :uploaded_videos do
    post :authorize_upload, :on => :collection
  end

  resources :uploaded_audios do
    post :authorize_upload, :on => :collection
  end

  resources :ajax, :controller => :ajax, :only => :none do
    get :soundcloud_embed, :on => :collection
  end
  get "/feed/:item_id/toggler" => "ajax#feed_item_toggler", :as => :feed_toggler
  get "/change/:playlist_id/cover_from/:item_id" => "ajax#change_playlist_cover_from_media", :as => :playlist_cover_changer

  resources :friend_maps do
    get :pending_friends, :on => :collection
    get :request_friends, :on => :collection
    get :friends, :on => :collection
    post :add_friend, :on => :collection
    post :agree_request, :on => :collection
    get :friends_feed, :on => :collection
  end

  resources :photos, :only => [:show, :update, :destroy]
  resources :albums, :only => [:show, :update, :destroy] do
    delete :delete_photo, :on => :collection
  end
  resources :tracks, :only => [:show, :update, :destroy]
  resources :videos, :only => [:show, :update, :destroy] do
    member do
      get :preview
    end
  end

  get '/:username' => "users#show"

  resources :track_albums, :only => [:show] do
    delete :delete_track, :on => :collection
  end

  resources :video_albums, :only => [:show] do
    delete :delete_video, :on => :collection
  end

 match '/users/sign_in' => "devise/sessions#new", :as => :create_user_session

end

app/models/uploaded_audio.rb
require 'open-uri'
require 'stringio'
require 'net/http'
require 'uri'
require 'mp3info'

class UploadedAudio < ActiveRecord::Base
  attr_accessible :panda_audio_id, :title, :user_id, :artist, :album, :genre, :music_photo
  validates_presence_of :panda_audio_id

  belongs_to :user

  after_destroy { panda_audio.delete }

  has_one :item, :as => :itemizable, :dependent => :destroy
  has_one :playlist, :through => :item
  has_one :content_control, :as => :itemizable, :dependent => :destroy

  acts_as_taggable

  def image_url
    "https://a1.sndcdn.com/images/default_avatar_large.png?3eddc42"
  end

  def music_url
    original_audio = panda_audio.encodings["mp3"]
    original_audio.url rescue nil
  end

  def panda_audio
    @panda_audio ||= Panda::Video.find(panda_audio_id)
  end

  def encode_success?
    panda_audio.encodings["mp3"].status == "success"
  end

  def ori_audio_url
    panda_audio.encodings["mp3"].url
  end

  def fetch_meta
    url = URI.parse(self.panda_audio.url)
    http = Net::HTTP.new(url.host, url.port)
    req = Net::HTTP::Get.new(url.path) # init a request with the url
    #req.range = (0..40960) # limit the load to only 4096 bytes
    res = http.request(req) # load the mp3 file
    child = {} # prepare an empty hash to store the metadata we grab
    Mp3Info.open(StringIO.open(res.body)) do |m|  #do the parsing
      child['title'] = m.tag.title
      child['artist'] = m.tag.artist
      child['album'] = m.tag.album
      child['genre'] = m.tag.genre_s

      #Cover Art
      pictures = m.tag2.pictures # array of images
      unless pictures.empty?
        pic = pictures[0]
        desc, data = pic[0], pic[1]
        file_name = "uploaded_audio_#{id}_#{desc}"
        File.binwrite(file_name, data)
        child['music_photo'] = File.new(file_name, "r")
      end
    end

    add_to_album child['album']


    # update uploaded_audio
    self.update_attributes child
    # delete temp file
    File.delete(child['music_photo'].path) if child['music_photo']
  end


  def add_to_album album_name
    user = self.user
    playlist = user.music_playlists.where(:social_network => 'Upload').first
    album_name ||= "Unknown" if album_name.empty?

    album = playlist.collections.where(:title => album_name).first_or_initialize
    if album.new_record?
      album.save!
      playlist.collections << album
    end


    album.uploaded_audios << self
  end

  unless Rails.env.development?
    paperclip_opts = {
        :storage => :fog,
        :fog_credentials => {:provider => "Local", :local_root => "public"},
        :fog_directory => "",
        :fog_host => "http://66.228.51.151:83",
        :styles => Proc.new { |clip| clip.instance.styles },
        #:url  => "/assets/vehicles/:id/:style/:basename.:extension",
        :path => "system/music_photo/:id/:style/:basename.:extension"
    }
  else
    paperclip_opts = {
        :storage => :fog,
        :fog_credentials => {:provider => "Local", :local_root => "public"},
        :fog_directory => "",
        :fog_host => "http://localhost:3000",
        :styles => Proc.new { |clip| clip.instance.styles },
        #:url  => "/assets/vehicles/:id/:style/:basename.:extension",
        :path => "system/music_photo/:id/:style/:basename.:extension"
    }
  end


  has_attached_file :music_photo, paperclip_opts

  def styles
    {}
  end

end

app/controllers/uploaded_audios_controller.rb
class UploadedAudiosController < ApplicationController

  layout 'blendwith'
  skip_before_filter :verify_authenticity_token

  def new
    @audios = current_user.uploaded_audios
    @playlist = current_user.music_playlists.where(social_network: 'Upload').first_or_create(name: 'Uploaded Music')
    @music_items = current_user.music_items.association_includer.with_playlist(@playlist)
  end

  def create
    audio = current_user.uploaded_audios.create(params[:audio])
    MetaWorker.perform_async(audio.id)
    redirect_to new_uploaded_audio_url
  end

  def update
    @track = UploadedAudio.find params[:id]
    if params[:tags]
      @track.title = params[:caption]
      @track.tag_list = params[:tags]
      @track.save
      redirect_to :back || new_uploaded_audio_url
    else
      @audio.update_attributes(params[:uploaded_audio])
      redirect_to new_uploaded_audio_url
    end
  end

  def destroy
    UploadedAudio.find(params[:id]).destroy
    render :nothing => true
  end

  def authorize_upload
    payload = JSON.parse(params['payload'])
    upload = Panda.post('/videos/upload.json', {
        file_name: payload['filename'],
        file_size: payload['filesize'],
        profiles: "mp3",
    })
    render :json => {:upload_url => upload['location']}
  end
  
end

app/views/uploaded_audios/new.html.erb
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" media="screen" />

<!-- Main data container -->

<div class="row-fluid">
  <%= render :partial => 'left_nav' %>
  <article class="span10 special">
    <div class="content">

      <div class="row-fluid">
        <div class="center">
          <!-- Secondary navigation -->
        </div>
        <div class="span10 center">
          <div class="nav-secondary">
            <%= render :partial => 'music_networks/social_nav' %>
          </div>
          <!-- /Secondary navigation -->
        </div>
      </div>

      <div class="row-fluid">
        <div class="page-header custom">
          <h3>
            <small>Select all | Select none</small>
          </h3>
        </div>
      </div>

      <div class="row-fluid" style="margin-top: 10px;">
        <%= form_tag uploaded_audios_path, id: "new_uploaded_audio" do |f| %>
          <!-- field where the audio ID will be stored after the upload -->
          <input type="hidden" name="audio[panda_audio_id]" id="panda_audio_id"/>

          <!-- upload progress bar (optional) -->
          <div class='progress'><span id="progress-bar" class='bar'></span></div>

          <input type="text" name='audio[title]' placeholder="Caption here" style="display: inline-block;margin-bottom: 0;">

          <!-- file selector -->
          <div id="browse" class="btn btn-success" style="display: inline-block;">
            <i class="icon-plus icon-white"></i>
            <span class="upload-btn">Add Audios...</span>
          </div>
        <% end %>
      </div>
      <br />
      <br />
      <br />
<%#= render 'shared/audio_player' %>
      <%= render 'shared/audiojs_player' %>
      <br />
      <br />
      <br />

      <div class="row-fluid">
        <div class="page-container">
            <form class="form-gallery">
              <ul id="thumbnails">
                <li class="span12"></li>
                <%= render partial: "music_partial", :collection => @music_items, as: :item, locals: { playlist: @playlist, network: ''}  %>
              </ul>
            </form>
            <%= render 'application/edit_form' %>
        </div>
      </div>
    </div>
  </article>
</div>
<script type="text/javascript">
  panda.uploader.init({
    'buttonId': 'browse',
    'progressBarId': 'progress-bar',
    'authorizeUrl': '/uploaded_audios/authorize_upload',
    'onSuccess': function(file, data) {
      $("#panda_audio_id").val(data.id)
    },
    'onComplete': function() {
      $("#new_uploaded_audio").submit();
    }
  });

<%#*$(document).ready(function () {%>
<%#*$("#jquery_jplayer_1").jPlayer({%>
<%#*ready: function () {%>
<%#*},%>
<%#*swfPath: "/js",%>
<%#*supplied: "m4a, oga"%>
<%#*});%>

<%#*$(".music-label input").click(function () {%>
<%#*var music = $(this).val();%>
<%#*$("#jquery_jplayer_1").jPlayer("setMedia", { m4a: music });%>
<%#*$(".jp-title ul li").html($(this).parent().text());%>
<%#*$("#jquery_jplayer_1").jPlayer("play");%>
<%#*});%>
<%#*});%>
</script>
<%= render "audio_control" %>