config/routes.rb
Blendwith::Application.routes.draw do

  root :to => "public#index"

  get "/tour" => "public#tour"
  opinio_model :controller => 'my_comments'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :video_urls
  resources :uploaded_photos
  resources :collections

  resources :music_urls do
    post :create_all, :on => :collection
  end

  resources :photo_urls, :only => [:new, :create, :destroy, :update] do
    delete 'delete_many', :on => :collection
  end

  match '/auth/:provider/callback' => 'services#create'
  resources :services, :only => [:index, :create]

  match "/facebook" => "image_playlists#show"
  match "/instagram" => "image_playlists#show"
  match "/googleplus" => "image_playlists#show"
  match "/twitter" => "image_playlists#show"
  match "/flickr" => "image_playlists#show"
  match "/soundcloud" => "music_playlists#show"
  match "/youtube" => "video_playlists#show"

  match "/uploader" => "photo_networks#uploader"
  put "/update_uploader/:id" => "photo_networks#update_uploader", :as => :update_photo_uploader

  post "/playlist_box_session" => "home#playlist_box_session"
  get "home/:social/social_login" => "home#social_login"
  get "/tour/update"    => "friend_maps#update_tour"

  devise_for :users, :controllers => { :omniauth_callbacks => 'services', :sessions => "users/sessions" }

  resources :playlists, :only => [:update, :destroy] do
    post :toggle_feed, :on => :member
  end

  resources :image_playlists do
    post 'add_item', :on => :member
    delete 'delete_media', :on => :collection
    get :image_playlist_by_id, :on => :member
    get :background_music_list, :on => :collection
    get :recent, :on => :collection
  end
  
  resources :music_playlists do
    post 'add_item', :on => :member
    delete :delete_item, :on => :collection
    put :update_track, :on => :member, :as => :update_track
  end

  resources :video_playlists do
    post 'add_item', :on => :member
    delete :delete_item, :on => :collection
  end

  get "/embed/:token" => "users#embed"

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :inbox
      get :sent_box
      get :trash_box
    end
  end

  resources :users, :only => [:show, :edit, :update, :destroy] do
    opinio
    post :privacy, :on => :collection
    post :friend_request, :on => :collection
    get :connect_social_network, :on => :collection
    post :disconnect_social_network, :on => :collection
    put :update_password, :on => :collection
    get :new_twitter_user, :on => :collection
    post :create_twitter_user, :on => :collection
    get :user_comments, :on => :member
    resources :uploaded_photos do
      collection do
        post :upload_photos
      end
    end
    resources :cover_photos do
      collection do
        post :upload_photos
      end
    end
    resources :profile_photos do
      collection do
        post :upload_photos
      end
    end
  end

  post "users/user-gallery.php" => "users#user_gallery"
  post "users/ajax-gallery.php" => "users#ajax_gallery"
  post "users/player.php" => "users#player"
  post "users/user_gallery_album" => "users#user_gallery_album"
  post "users/photo_player" => "users#photo_player"

  resources :uploaded_videos do
    post :authorize_upload, :on => :collection
  end

  resources :uploaded_audios do
    post :authorize_upload, :on => :collection
  end

  resources :ajax, :controller => :ajax, :only => :none do
    get :soundcloud_embed, :on => :collection
  end
  get "/feed/:item_id/toggler" => "ajax#feed_item_toggler", :as => :feed_toggler
  get "/change/:playlist_id/cover_from/:item_id" => "ajax#change_playlist_cover_from_media", :as => :playlist_cover_changer

  resources :friend_maps do
    get :pending_friends, :on => :collection
    get :request_friends, :on => :collection
    get :friends, :on => :collection
    post :add_friend, :on => :collection
    post :agree_request, :on => :collection
    get :friends_feed, :on => :collection
  end

  resources :photos, :only => [:show, :update, :destroy]
  resources :albums, :only => [:show, :update, :destroy] do
    delete :delete_photo, :on => :collection
  end
  resources :tracks, :only => [:show, :update, :destroy]
  resources :videos, :only => [:show, :update, :destroy] do
    member do
      get :preview
    end
  end

  get '/:username' => "users#show"

  resources :track_albums, :only => [:show] do
    delete :delete_track, :on => :collection
  end

  resources :video_albums, :only => [:show] do
    delete :delete_video, :on => :collection
  end

 match '/users/sign_in' => "devise/sessions#new", :as => :create_user_session

end

app/controllers/track_albums_controller.rb
class TrackAlbumsController < ApplicationController

  layout 'blendwith'

  before_filter :authorize_user

  skip_before_filter :verify_authenticity_token, :only => :delete_track

  def show
    @track_album = TrackAlbum.find(params[:id].to_i)
  end

  def delete_track
    track = Track.find params[:track_id]
    track.destroy
    render :nothing => true
  end

end

app/views/track_albums/_track.html.erb
<% data = { type: 'track', id: track.id, network: 'soundcloud', title: track.title, tags: track.tags.map(&:name).join(","), url: track_path(track) } %>
<%= content_tag :li, data: data, class: 'span3 with-title audio-li thumbnail' do %>
    <%= track.title %>
    <%= link_to "Play", "#", class: 'play', data: {track_id: track.social_network_id} %>
    <%= content_tag :div, "", :id => "track-#{track.social_network_id}", :class => "track-preview" %>
    <div class="player">
      <span class="play-button"></span>
      <span class="progress-bar"></span>
    </div>

    <div>
      <a href="#demoModal" data-toggle="modal" class="awe-trash"></a>
    </div>

<% end %>

app/views/track_albums/show.html.erb
<!-- Main data container -->
<div>

  <div class="row-fluid">
    <%= render :partial => 'left_nav' %>
    <article class="span10 special">
      <div class="content">
        <div class="row-fluid">
          <div class="center">
            <h2 class="orange">Add My Music</h2>
            <!-- Secondary navigation -->
          </div>
          <div class="span10 center">
            <div class="nav-secondary">
              <%= render 'music_networks/social_nav' %>
            </div>
            <!-- /Secondary navigation -->
          </div>
        </div>
        <div class="row-fluid">
          <div class="page-header custom">
            <h3>
              <%= @track_album.name %>
              <br>
              <small>Select all | Select none</small>
            </h3>
          </div>
        </div>
        <div class="row-fluid">
          <div class="page-container">
            <form class="form-gallery">
              <ul id="thumbnails" class="thumbnails">
                <%#= render :partial => '' %>
                <% @track_album.tracks.each do |track| %>
                    <%= render :partial => 'track', :locals => {track: track} %>
                <% end %>
              </ul>
            </form>
          </div>
        </div>

      </div>

    </article>
  </div>
</div>
<%= javascript_include_tag 'http://connect.soundcloud.com/sdk.js'%>
<script type="text/javascript">
    $(function() {
        SC.initialize({
            client_id:  '<%= CONFIG[:soundcloud][:client_id] %>',
            access_token: '<%= current_user.soundcloud.try(:access_token) %>'
        });
    });
</script>
<%= javascript_include_tag 'soundcloud' %>